### ISSUE TITLE
Failed to spawn script message on v1.4

### ISSUE THREAD

**Issue by spetragl** [openconnect/openconnect-gui#124] opened 2016-08-16 12:56 UTC
I get this message in v1.4 
"Failed to spawn script 'C:/Program Files (x86)/OpenConnect 1.4\vpnc-script.js' for connect: There are no more files." 
somewhere after it identifies the TAP Device and before it runs the "Pre-Init".
Oddly enough, all of my Network Routes set up in the "connect" section of  vpnc-script.js  work perfectly.

2016-08-16 08:03 CSTP connected. DPD 90, Keepalive 20
2016-08-16 08:03 CSTP Ciphersuite: (TLS1.0)-(RSA)-(AES-128-CBC)-(SHA1)
2016-08-16 08:03 Opened tun device My-TAP
2016-08-16 08:03 TAP-Windows driver v9.21 (0)
2016-08-16 08:03 Failed to spawn script 'C:/Program Files (x86)/OpenConnect 1.4\vpnc-script.js' for connect: There are no more files.
2016-08-16 08:03 vpnc-script.js STARTED Tue Aug 16 08:03:21 EDT 2016
2016-08-16 08:03 >PRE-INIT done.
2016-08-16 08:03 vpnc-script.js ENDED Tue Aug 16 08:03:21 EDT 2016
2016-08-16 08:03 vpnc-script.js STARTED Tue Aug 16 08:03:21 EDT 2016
2016-08-16 08:03 >CONNECT
2016-08-16 08:03 >executing: route print
2016-08-16 08:03 <<-- [EXEC] route print

**Comment by horar** [comment] 2016-09-01 22:17
Hi, this message come from openconnect library, looks like this error string appears sometimes with different software too. I don't know what we can do with... :/

**Comment by horar** [comment] 2017-04-09 23:13
Hi @spetragl ; I don't know what can we do with this in GUI. Moreover it looks that script was started by openconnect library.
Closing now, feel free re-open when you get new info OR when it is reproducible with console openconnect, we can discuss this with openconnect author in upstream openconnect mailing list.
Thanks

**Closed by horar** 2017-04-09 23:13 UTC
Labels: component:openconnect
