### ISSUE TITLE
Batch Mode isn't saving password persistently

### ISSUE THREAD

**Issue by sugarbombed** [openconnect/openconnect-gui#209] opened 2017-12-18 20:58 UTC
### Description of the Issue
When logging into the VPN with batch mode selected on the profile, the password is remembered properly.

Occasionally manual disconnects (or seemingly every instance when the server causes a disconnect), a password will be prompted to be re-entered.

### Specifications
- **Version**: 1.5.2 (32 bit)
- **Platform**: Windows 10 64 bit
### Steps to Reproduce the Issue
1. Enable batch mode and enter password like normal.
2. Manually disconnect (this won't always cause this bug).
3. Have the server disconnect the VPN (or a possible internet loss)

### Expected Behavior
I shouldn't have to re-enter the password from my understanding

### Actual Behavior
The password prompt appears. The log shows that the Password form in vpninfo.cpp on like 206 is firing.

### Other Information
I'm wondering if this has something to do with attempting to reconnect and when it can't, removing the saved password.

i.e

- Server disconnects
- Application attempts to reconnect and fails. Repeat several times. At this point, does it possibly remove the stored password?
- When reconnecting manually, it asks for password.

**Comment by horar** [comment] 2017-12-18 21:15
As stated in previous tickets, batch mode is broken at this time. But, yes - it will be fixed...

**Comment by sugarbombed** [comment] 2017-12-18 21:23
Whoops sorry. I did a quick search and didn't see it referenced anywhere.

**Comment by horar** [comment] 2018-01-15 02:15
Np (duplicate of #142)

**Closed by horar** 2018-01-15 02:15 UTC
