### ISSUE TITLE
Error with saved credential using PAM Authentication

### ISSUE THREAD

**Issue by MADAO541807** [openconnect/openconnect-gui#200] opened 2017-11-07 17:59 UTC
### Description of the Issue
I have an openconnect server running on Debian with Self-Signed certificate and using only PAM authentication. Users can login flawlessly at first time, but a second time they cannot login. It seems to be an issue with stored username and password since if you edit the profile and clear the username stored, save it and try to login again, the window asking for username will show up and providing the username, it will connect (generally, without asking for a password).

### Specifications
- **Version**: 1.52
- **Platform**: Windows 10 pro x64 (pt-br)

### Steps to Reproduce the Issue
1. Create a profile, specifying a name (use customize checkbox) and server:port to connect
2. Click connect, using the created profile.
3. Disconnect and try to connect again, after a few seconds, you will be disconnected.

### Expected Behavior
You should connect again, using stored username and password.

### Actual Behavior
It tries to connect, but after over 5 seconds, connection attempt is unsuccessful.

### Other Information
First connection (successful):
2017-11-07 14:28:35 | 20fc | Got HTTP response: HTTP/1.1 200 OK

2017-11-07 14:28:35 | 20fc | Set-Cookie: webvpncontext=<REMOVED>; Max-Age=300; Secure

2017-11-07 14:28:35 | 20fc | Content-Type: text/xml

2017-11-07 14:28:35 | 20fc | Content-Length: 310

2017-11-07 14:28:35 | 20fc | X-Transcend-Version: 1

2017-11-07 14:28:35 | 20fc | HTTP body length:  (310)

2017-11-07 14:28:35 | 20fc | Please enter your password.

2017-11-07 14:28:35 | 20fc | Password form: password

2017-11-07 14:28:42 | 20fc | POST https://<REMOVED>/auth

2017-11-07 14:28:42 | 20fc | Got HTTP response: HTTP/1.1 200 OK

Attempt (connection unsuccessful):

2017-11-07 12:49:52 | 11b8 | Content-Type: text/xml

2017-11-07 12:49:52 | 11b8 | Content-Length: 306

2017-11-07 12:49:52 | 11b8 | X-Transcend-Version: 1

2017-11-07 12:49:52 | 11b8 | HTTP body length:  (306)

2017-11-07 12:49:52 | 11b8 | XML POST enabled

2017-11-07 12:49:52 | 11b8 | Please enter your username.

2017-11-07 12:49:52 | 11b8 | Text form: username

2017-11-07 12:49:52 | 11b8 | Authentication failed in batch mode, retrying with batch mode disabled

2017-11-07 12:49:52 | 11b8 | POST https://<REMOVED>/auth

2017-11-07 12:49:52 | 11b8 | Attempting to connect to server <REMOVED>

2017-11-07 12:49:52 | 11b8 | Connected to <REMOVED>

2017-11-07 12:49:52 | 11b8 | SSL negotiation with <REMOVED>

2017-11-07 12:49:53 | 11b8 | Server certificate verify failed: signer not found

2017-11-07 12:49:54 | 11b8 | Connected to HTTPS on <REMOVED>

2017-11-07 12:49:54 | 11b8 | Got HTTP response: HTTP/1.1 200 OK

2017-11-07 12:49:54 | 11b8 | Set-Cookie: webvpncontext=; expires=Thu, 01 Jan 1970 22:00:00 GMT; path=/; Secure

2017-11-07 12:49:54 | 11b8 | Content-Type: text/xml

2017-11-07 12:49:54 | 11b8 | Content-Length: 306

2017-11-07 12:49:54 | 11b8 | X-Transcend-Version: 1

2017-11-07 12:49:54 | 11b8 | HTTP body length:  (306)

2017-11-07 12:49:54 | 11b8 | XML POST enabled

2017-11-07 12:49:54 | 11b8 | Please enter your username.

2017-11-07 12:49:54 | 11b8 | Text form: username

2017-11-07 12:49:54 | 2248 | Disconnected

It logs a Text form: username, but no screen/window is visible to user and connection is not completed.

**Comment by williamswhy** [comment] 2017-12-10 02:52
Same problem here. Do you have any solution?

**Comment by horar** [comment] 2017-12-10 21:17
I have suspicion... something similar was already reported.

Let's try something, could you please try this:
- remove existing profile
- create new profile in advanced mode
- enter the same configuration data
- don't enable batch mode!
- try connect.... disconnect and connect again.

Thanks...

**Comment by williamswhy** [comment] 2017-12-10 21:42
I tried to solve this problem by editing the code and I found that there might be a problem with the encrypt/decrypt method. This is what I got from the decrypted password which is obviously incorrect.
![image](https://user-images.githubusercontent.com/13313931/33809687-c813977a-ddc8-11e7-9633-e3e31edd747e.png)
Hopefully, this can help you a little bit.

**Comment by williamswhy** [comment] 2017-12-10 21:55
By the way, everything works fine with batch mode disabled.

**Comment by horar** [comment] 2017-12-10 22:07
@williamswhy thanks for hint, there are more problems :/ ... will look to this in January, I'm working on some cleanup... :-)

**Comment by MADAO541807** [comment] 2017-12-13 15:49
Hi
Yes, as susggested, disabling "Batch Mode" asks for password and user can login. The issue seems to be, indeed, with credentials saved, but for me at least, having users to input password works fine.

**Comment by horar** [comment] 2018-01-15 02:19
From description looks like similar problem with batch-mode and password store (duplicate of #142)

**Closed by horar** 2018-01-15 02:19 UTC
