### ISSUE TITLE
Password isn't remembered; batch mode enabled

### ISSUE THREAD

**Issue by jairov4** [openconnect/openconnect-gui#227] opened 2018-03-15 03:52 UTC
### Description of the Issue
Password is asked if PC is rebooted

### Specifications
- **1.4.1**: 
- **Windows 10 64-bit**: 

### Steps to Reproduce the Issue

1. enable batch mode, setup your TOTP key
2. connect vpn
3.  disconnect vpn and turn off your pc
4. forget about this for 1 week
5. turn on your pc and connect vpn

### Expected Behavior
batch mode should keep my password and stop bother asking me for this forever

### Actual Behavior

password is asked

**Comment by horar** [comment] 2018-03-15 20:57
Duplicate of #142; fixed in source code - will be released with v1.5.3

**Closed by horar** 2018-03-15 20:57 UTC
