### ISSUE TITLE
batch mode not working in 1.5.2 

### ISSUE THREAD

**Issue by goduck777** [openconnect/openconnect-gui#219] opened 2018-01-29 15:03 UTC
### Description of the Issue
Batch mode for saved password is not working at 1.5.2

### Specifications
- **Version**: 1.5.2
- **Platform**: Windows10

### Steps to Reproduce the Issue
After saving a vpn password with batch mode turned on, the vpn cannot be logged in next time.

### Other Information
The log is
```
2018-01-29 09:56:50 | 2f00 | OpenConnect-GUI VPN client (1.5.2) logging started...
2018-01-29 09:56:53 | 3150 | GET https://vpn.pppl.gov/
2018-01-29 09:56:53 | 3150 | Attempting to connect to server 192.188.106.249:443
2018-01-29 09:56:53 | 3150 | Connected to 192.188.106.249:443
2018-01-29 09:56:53 | 3150 | There was a non-CA certificate in the trusted list: OU=Copyright (c) 1997 Microsoft Corp.,OU=Microsoft Corporation,CN=Microsoft Root Authority.
2018-01-29 09:56:53 | 3150 | There was a non-CA certificate in the trusted list: C=US,ST=California,L=Irvine,O=Blizzard Entertainment,OU=Battle.net,CN=Blizzard Battle.net Local Cert.
2018-01-29 09:56:53 | 3150 | There was a non-CA certificate in the trusted list: C=US,O=MSFT,CN=Microsoft Authenticode(tm) Root Authority.
2018-01-29 09:56:53 | 3150 | There was a non-CA certificate in the trusted list: CN=CORP\\srv-build-cd.
2018-01-29 09:56:53 | 3150 | There was a non-CA certificate in the trusted list: C=US,postalCode=08544,ST=New Jersey,L=Princeton,street=One Nassau Hall,O=The Trustees of Princeton University,OU=OIT,CN=cppm-04.princeton.edu.
2018-01-29 09:56:53 | 3150 | There was a non-CA certificate in the trusted list: C=US,postalCode=08544,ST=New Jersey,L=Princeton,street=One Nassau Hall,O=The Trustees of Princeton University,OU=OIT,CN=cppm-03.princeton.edu.
2018-01-29 09:56:53 | 3150 | There was a non-CA certificate in the trusted list: C=US,postalCode=08544,ST=New Jersey,L=Princeton,street=One Nassau Hall,O=The Trustees of Princeton University,OU=OIT,CN=cppm-master.princeton.edu.
2018-01-29 09:56:53 | 3150 | There was a non-CA certificate in the trusted list: CN=Root Agency.
2018-01-29 09:56:53 | 3150 | SSL negotiation with vpn.pppl.gov
2018-01-29 09:56:53 | 3150 | Connected to HTTPS on vpn.pppl.gov
2018-01-29 09:56:53 | 3150 | Got HTTP response: HTTP/1.1 302 Found
2018-01-29 09:56:53 | 3150 | Location: https://vpn.pppl.gov/dana-na/auth/url_default/welcome.cgi
2018-01-29 09:56:53 | 3150 | Content-Type: text/html; charset=utf-8
2018-01-29 09:56:53 | 3150 | Set-Cookie: DSSIGNIN=url_default; path=/dana-na/; expires=Thu, 31-Dec-2037 00:00:00 GMT; secure
2018-01-29 09:56:53 | 3150 | Set-Cookie: DSIVS=; path=/; expires=Thu, 01 Jan 1970 22:00:00 GMT; secure
2018-01-29 09:56:53 | 3150 | Set-Cookie: DSSignInURL=/; path=/; secure
2018-01-29 09:56:53 | 3150 | Connection: close
2018-01-29 09:56:53 | 3150 | Content-Length: 0
2018-01-29 09:56:53 | 3150 | HTTP body length:  (0)
2018-01-29 09:56:53 | 3150 | GET https://vpn.pppl.gov/dana-na/auth/url_default/welcome.cgi
2018-01-29 09:56:53 | 3150 | SSL negotiation with vpn.pppl.gov
2018-01-29 09:56:53 | 3150 | Connected to HTTPS on vpn.pppl.gov
2018-01-29 09:56:53 | 3150 | Got HTTP response: HTTP/1.1 200 OK
2018-01-29 09:56:53 | 3150 | Content-Type: text/html; charset=utf-8
2018-01-29 09:56:53 | 3150 | Date: Mon, 29 Jan 2018 14:56:55 GMT
2018-01-29 09:56:53 | 3150 | Connection: close
2018-01-29 09:56:53 | 3150 | Pragma: no-cache
2018-01-29 09:56:53 | 3150 | Cache-Control: no-store
2018-01-29 09:56:53 | 3150 | Expires: -1
2018-01-29 09:56:53 | 3150 | X-Frame-Options: SAMEORIGIN
2018-01-29 09:56:53 | 3150 | HTTP body http 1.0 (-1)
2018-01-29 09:56:53 | 3150 | SSL socket closed uncleanly
2018-01-29 09:56:53 | 3150 | Ignoring unknown form submit item 'sn-preauth-decline'
2018-01-29 09:56:53 | 3150 | This is a Federal computer system (and/or it is directly connected to a
PPPL local network system) and is the property of the United States
Government. It is for authorized use only. Users (authorized or
unauthorized) have no explicit or implicit expectation of privacy.

Any or all uses of this system and all files on this system may be
intercepted, monitored, recorded, copied, audited, inspected, and
disclosed to authorized site, Department of Energy, and law enforcement
personnel, as well as authorized officials of other agencies, both
domestic and foreign. By using this system, the user consents to such
interception, monitoring, recording, copying, auditing, inspection, and
disclosure at the discretion of authorized site or Department of Energy
personnel.

Unauthorized or improper use of this system may result in administrative
disciplinary action and civil and criminal penalties. By continuing to
use this system you indicate your awareness of and consent to these
terms and conditions of use. LOG OFF IMMEDIATELY if you do not agree to
the conditions stated in this warning.
2018-01-29 09:56:53 | 3150 | unknown type 4
2018-01-29 09:56:53 | 3150 | POST https://vpn.pppl.gov/dana-na/auth/url_default/welcome.cgi
2018-01-29 09:56:53 | 3150 | SSL negotiation with vpn.pppl.gov
2018-01-29 09:56:53 | 3150 | Connected to HTTPS on vpn.pppl.gov
2018-01-29 09:56:53 | 3150 | Got HTTP response: HTTP/1.1 302 Moved
2018-01-29 09:56:53 | 3150 | Set-Cookie: DSSigninNotif=1; path=/; secure
2018-01-29 09:56:53 | 3150 | Date: Mon, 29 Jan 2018 14:56:55 GMT
2018-01-29 09:56:53 | 3150 | location: https://vpn.pppl.gov/dana-na/auth/url_default/welcome.cgi?
2018-01-29 09:56:53 | 3150 | Connection: close
2018-01-29 09:56:53 | 3150 | Pragma: no-cache
2018-01-29 09:56:53 | 3150 | Cache-Control: no-store
2018-01-29 09:56:53 | 3150 | Expires: -1
2018-01-29 09:56:53 | 3150 | HTTP body http 1.0 (-1)
2018-01-29 09:56:53 | 3150 | SSL socket closed uncleanly
2018-01-29 09:56:53 | 3150 | GET https://vpn.pppl.gov/dana-na/auth/url_default/welcome.cgi?
2018-01-29 09:56:53 | 3150 | SSL negotiation with vpn.pppl.gov
2018-01-29 09:56:53 | 3150 | Connected to HTTPS on vpn.pppl.gov
2018-01-29 09:56:53 | 3150 | Got HTTP response: HTTP/1.1 200 OK
2018-01-29 09:56:53 | 3150 | Content-Type: text/html; charset=utf-8
2018-01-29 09:56:53 | 3150 | Date: Mon, 29 Jan 2018 14:56:55 GMT
2018-01-29 09:56:53 | 3150 | x-frame-options: SAMEORIGIN
2018-01-29 09:56:53 | 3150 | Connection: close
2018-01-29 09:56:53 | 3150 | Pragma: no-cache
2018-01-29 09:56:53 | 3150 | Cache-Control: no-store
2018-01-29 09:56:53 | 3150 | Expires: -1
2018-01-29 09:56:53 | 3150 | HTTP body http 1.0 (-1)
2018-01-29 09:56:53 | 3150 | SSL socket closed uncleanly
2018-01-29 09:56:53 | 3150 | frmLogin
2018-01-29 09:56:53 | 3150 | unknown type 4
2018-01-29 09:56:53 | 3150 | Text form: username
2018-01-29 09:56:53 | 3150 | Password form: password
2018-01-29 09:56:53 | 3150 | unknown type 4
2018-01-29 09:56:53 | 3150 | unknown type 4
2018-01-29 09:56:53 | 3150 | Authentication failed in batch mode, retrying with batch mode disabled
2018-01-29 09:56:53 | 3150 | GET https://vpn.pppl.gov/dana-na/auth/url_default/welcome.cgi?
2018-01-29 09:56:53 | 3150 | Attempting to connect to server 192.188.106.249:443
2018-01-29 09:56:53 | 3150 | Connected to 192.188.106.249:443
2018-01-29 09:56:53 | 3150 | SSL negotiation with vpn.pppl.gov
2018-01-29 09:56:54 | 3150 | Connected to HTTPS on vpn.pppl.gov
2018-01-29 09:56:54 | 3150 | Got HTTP response: HTTP/1.1 200 OK
2018-01-29 09:56:54 | 3150 | Content-Type: text/html; charset=utf-8
2018-01-29 09:56:54 | 3150 | Date: Mon, 29 Jan 2018 14:56:55 GMT
2018-01-29 09:56:54 | 3150 | Connection: close
2018-01-29 09:56:54 | 3150 | Pragma: no-cache
2018-01-29 09:56:54 | 3150 | Cache-Control: no-store
2018-01-29 09:56:54 | 3150 | Expires: -1
2018-01-29 09:56:54 | 3150 | X-Frame-Options: SAMEORIGIN
2018-01-29 09:56:54 | 3150 | HTTP body http 1.0 (-1)
2018-01-29 09:56:54 | 3150 | SSL socket closed uncleanly
2018-01-29 09:56:54 | 3150 | Ignoring unknown form submit item 'sn-preauth-decline'
2018-01-29 09:56:54 | 3150 | This is a Federal computer system (and/or it is directly connected to a
PPPL local network system) and is the property of the United States
Government. It is for authorized use only. Users (authorized or
unauthorized) have no explicit or implicit expectation of privacy.

Any or all uses of this system and all files on this system may be
intercepted, monitored, recorded, copied, audited, inspected, and
disclosed to authorized site, Department of Energy, and law enforcement
personnel, as well as authorized officials of other agencies, both
domestic and foreign. By using this system, the user consents to such
interception, monitoring, recording, copying, auditing, inspection, and
disclosure at the discretion of authorized site or Department of Energy
personnel.

Unauthorized or improper use of this system may result in administrative
disciplinary action and civil and criminal penalties. By continuing to
use this system you indicate your awareness of and consent to these
terms and conditions of use. LOG OFF IMMEDIATELY if you do not agree to
the conditions stated in this warning.
2018-01-29 09:56:54 | 3150 | unknown type 4
2018-01-29 09:56:54 | 3150 | Authentication failed in batch mode, retrying with batch mode disabled
2018-01-29 09:56:54 | 3150 | GET https://vpn.pppl.gov/dana-na/auth/url_default/welcome.cgi?
2018-01-29 09:56:54 | 3150 | Attempting to connect to server 192.188.106.249:443
2018-01-29 09:56:54 | 3150 | Connected to 192.188.106.249:443
2018-01-29 09:56:54 | 3150 | SSL negotiation with vpn.pppl.gov
2018-01-29 09:56:54 | 3150 | Connected to HTTPS on vpn.pppl.gov
2018-01-29 09:56:54 | 3150 | Got HTTP response: HTTP/1.1 200 OK
2018-01-29 09:56:54 | 3150 | Content-Type: text/html; charset=utf-8
2018-01-29 09:56:54 | 3150 | Date: Mon, 29 Jan 2018 14:56:55 GMT
2018-01-29 09:56:54 | 3150 | Connection: close
2018-01-29 09:56:54 | 3150 | Pragma: no-cache
2018-01-29 09:56:54 | 3150 | Cache-Control: no-store
2018-01-29 09:56:54 | 3150 | Expires: -1
2018-01-29 09:56:54 | 3150 | X-Frame-Options: SAMEORIGIN
2018-01-29 09:56:54 | 3150 | HTTP body http 1.0 (-1)
2018-01-29 09:56:54 | 3150 | SSL socket closed uncleanly
2018-01-29 09:56:54 | 3150 | Ignoring unknown form submit item 'sn-preauth-decline'
2018-01-29 09:56:54 | 3150 | This is a Federal computer system (and/or it is directly connected to a
PPPL local network system) and is the property of the United States
Government. It is for authorized use only. Users (authorized or
unauthorized) have no explicit or implicit expectation of privacy.

Any or all uses of this system and all files on this system may be
intercepted, monitored, recorded, copied, audited, inspected, and
disclosed to authorized site, Department of Energy, and law enforcement
personnel, as well as authorized officials of other agencies, both
domestic and foreign. By using this system, the user consents to such
interception, monitoring, recording, copying, auditing, inspection, and
disclosure at the discretion of authorized site or Department of Energy
personnel.

Unauthorized or improper use of this system may result in administrative
disciplinary action and civil and criminal penalties. By continuing to
use this system you indicate your awareness of and consent to these
terms and conditions of use. LOG OFF IMMEDIATELY if you do not agree to
the conditions stated in this warning.
2018-01-29 09:56:54 | 3150 | unknown type 4
2018-01-29 09:56:54 | 2f00 | Disconnected
```

**Comment by horar** [comment] 2018-01-29 15:18
Thanks for log, I think this is duplicate of #142

**Closed by horar** 2018-01-29 15:18 UTC

**Comment by goduck777** [comment] 2018-01-29 15:21
I don't think this is the same as  I think this is duplicate of #142.

1. This happens all the time. Basically batch mode never works.
2. This only happens at 1.5.2. 1.5.1 works fine.
