### ISSUE TITLE
Unstable behavior wrt. vpnc-script.js

### ISSUE THREAD

**Issue by Adam5Wu** [openconnect/openconnect-gui#108] opened 2016-05-28 18:52 UTC
I am using 1.3 version on Windows with vpnc-script.js from develop branch, although I believe this problem is more possibly related to the main program.

Basically, upon the very first connect of an instance of the GUI, I can see from log window that vpnc-script.js is being executed correctly, and output captured and displayed in the log window;

Then I disconnect and connect again, the log message does not contain any message from vpnc-script.js anymore; the same for all future disconnect and connect.

Then I found a more weird case:
To check whether vpnc-script.js is executed in the 2nd+ connect events, I erased the tap adapter settings (replace static IP/DNS with DHCP) before Nth connection (N>1), and check whether the IP/DNS settings are correctly reconfigured by vpnc-script.js.

After I did that, at next connection, I noticed one more line in the log message, reads:
`Failed to spawn script 'vpnc-script.js' for connect: The handle is invalid.`
But, when I check adapter settings, all correct settings has been applied, which means that vpnc-script.js was indeed executed successfully.

So it seems at least there are three states the GUI program can be in:
1. Very first connect, this is the perfect state;
2. Subsequent connect without change in tap adapter settings
    This state either does not invoke vpnc-script.js, or the output was not captured to log window;
3. Subsequent connect after change in tap adapter settings
    This state does invoke vpnc-script.js, correctly, but the GUI think it failed with invalid handle errors.

**Comment by horar** [comment] 2016-09-12 20:51
Just played with 1.3/1.4.1 and tried to reproduce it.

The app has an issue, you probably know, to load vpnc script output into application log window, must be the log window closed/openend (yeap, just reimplementing logging...).

I don't face mentioned problems in 1 and 2 with both versions for 2nd
and later connect. I guess, there is other problem. Or I missundestood something :-)
I suggest to try 1.4.1 and share some logs. We can check if all steps
was successfull etc.

**Comment by horar** [comment] 2017-04-09 23:10
hi @Adam5Wu , there was couple of changes/fixes from that time. Logging should work better and I can't reproduce other problems.
I'm closing this for now. If you facing these problems, please re-open this ticket and add more info, logs etc.
Thanks

**Closed by horar** 2017-04-09 23:10 UTC
