### ISSUE TITLE
Default route flashback

### ISSUE THREAD

**Issue by caoli5288** [openconnect/openconnect-gui#170] opened 2017-03-31 16:17 UTC
### Description of the Issue
Once connected the client side's default route is change to vpn but flashback after few secends. It will be re-set to vpn randomly and cycling. The connection established without disconnect(ping private ip without drop packets)

### Specifications
- **Version**: ocserv-0.11.7 and openconnect-gui-1.5.1
- **Platform**: Tested on win7-64bit and win10-64bit

### Prerequisites
* [ ] Can you reproduce the problem? Yes.
* [ ] Are you running the latest version? Yes.

### Steps to Reproduce the Issue
1. Client to server
2. Wait a moment
3. The default route flashback.

### Expected Behavior
Descriped in description comment

### Actual Behavior
Descriped in description comment

### Other Information
Descriped in description comment

**Comment by horar** [comment] 2017-04-02 19:44
hi, could you please upload the log file?
thanks in advance

**Comment by caoli5288** [comment] 2017-04-06 08:13
http://paste.ubuntu.com/24326331/ @horar I have replaced my server's ip by "****". Config opetions here.
![qq20170406160805](https://cloud.githubusercontent.com/assets/3120587/24744242/e7ca9ec2-1ae3-11e7-81cd-ac356f12202c.png)

**Comment by horar** [comment] 2017-04-09 23:39
hi, there was reported few problems with non-ascii character for interface names.
These issues should be fixed by vpnc script.

Could you please try download this version of [vpnc-script.js](https://raw.githubusercontent.com/horar/vpnc-scripts/master/vpnc-script-win.js), rename/store them into installed folder and upload newest observations/log file?
Thanks

**Comment by caoli5288** [comment] 2017-04-10 04:51
@horar Hi. Seems even worse. No any router setup now. Log here. http://paste.ubuntu.com/24352805/

**Comment by horar** [comment] 2017-04-10 12:51
@caoli5288 it's not worst, just you don't have this environment variable; instead of environment variable, you can update the script:
<pre>
if (env("LOG2FILE")) {
	var fs = WScript.CreateObject("Scripting.FileSystemObject");
	var tmpdir = fs.GetSpecialFolder(2)+"\\";
	var log = fs.OpenTextFile(tmpdir + "vpnc.log", 8, true);
}
</pre>
to
<pre>
//if (env("LOG2FILE")) {
	var fs = WScript.CreateObject("Scripting.FileSystemObject");
	var tmpdir = fs.GetSpecialFolder(2)+"\\";
	var log = fs.OpenTextFile(tmpdir + "vpnc.log", 8, true);
//}
</pre>

The script is for newer version of app (not released yet)

**Comment by caoli5288** [comment] 2017-04-10 16:38
@horar Not this case... :-( I do this step before you comment.

**Comment by caoli5288** [comment] 2017-04-10 16:46
@horar You say the reason is non-ascii interface name. but no change after I rename "本地连接3" to "vpn3".
:-(
I do not know how to describe it...not any log line while default router change to vpn or back to my wifi router.

**Comment by horar** [comment] 2017-04-10 16:57
ehm, I don't have idea what's wrong from above info; may be few questions:
- that screenshot is from the win7/win10? looks like from application running via wine?
- do you run on native OS or in emulation?
- do you use other VPN tools or some proxies?

**Comment by istanleyyaw** [comment] 2017-04-10 23:06
I do have the exact problem here on my PC, I was think it was detectdeadroute registry work and VPN route dead it switch to backup gateway but even I disable it it still behavior the same. My adapter name is ASCII character. Now every time run VPN I need manually remove the original default route and add it back when close VPN

**Comment by istanleyyaw** [comment] 2017-04-10 23:11
Not always like that, sometimes okay.

**Comment by istanleyyaw** [comment] 2017-04-10 23:32
IPv4 Route Table
===========================================================================
Active Routes:
Network Destination        Netmask          Gateway       Interface  Metric
          0.0.0.0          0.0.0.0  192.168.254.254    192.168.254.3     25
          0.0.0.0          0.0.0.0       10.10.20.1      10.10.20.49      2
       10.10.20.0    255.255.255.0         On-link       10.10.20.49    257
      10.10.20.49  255.255.255.255         On-link       10.10.20.49    257
     10.10.20.255  255.255.255.255         On-link       10.10.20.49    257
  104.199.202.189  255.255.255.255  192.168.254.254    192.168.254.3     26
        127.0.0.0        255.0.0.0         On-link         127.0.0.1    306
        127.0.0.1  255.255.255.255         On-link         127.0.0.1    306
  127.255.255.255  255.255.255.255         On-link         127.0.0.1    306
    192.168.254.0    255.255.255.0         On-link     192.168.254.3    281
    192.168.254.3  255.255.255.255         On-link     192.168.254.3    281
  192.168.254.255  255.255.255.255         On-link     192.168.254.3    281
        224.0.0.0        240.0.0.0         On-link         127.0.0.1    306
        224.0.0.0        240.0.0.0         On-link     192.168.254.3    281
        224.0.0.0        240.0.0.0         On-link       10.10.20.49    257
  255.255.255.255  255.255.255.255         On-link         127.0.0.1    306
  255.255.255.255  255.255.255.255         On-link     192.168.254.3    281
  255.255.255.255  255.255.255.255         On-link       10.10.20.49    257
===========================================================================
Persistent Routes:
  Network Address          Netmask  Gateway Address  Metric
        10.3.36.1    255.255.255.0      20.2.217.34       1
      10.3.36.164  255.255.255.255       20.2.225.2       1
        10.3.30.1    255.255.255.0       20.2.225.2       1
        10.3.30.1    255.255.255.0      20.2.225.28       1
          0.0.0.0          0.0.0.0       10.10.20.1       1
===========================================================================

this is routing table. looks fine, but traffic always go from gateway  192.168.254.254, but I can ping the vpn gateway IP 10.10.20.1 at same time.

**Comment by caoli5288** [comment] 2017-04-11 05:06
@horar Screenshot is native win7-x64 on my laptop, with classic theme, without any other vpn.

**Comment by horar** [comment] 2017-04-11 21:35
@istanleyyaw @caoli5288 ok, thanks for update; can you try bundled openconnect console tool? If the problem is reproducible there, we should move this discussion to upsteam openconnect project and talk to author. This project is about GUI build on top of openconnect library.

**Comment by caoli5288** [comment] 2017-04-12 06:11
@horar Where I can download bundled openconnect console tool? Or I mush build it from source?

**Comment by horar** [comment] 2017-04-12 11:00
@caoli5288 it's an optional part of released installer

**Comment by caoli5288** [comment] 2017-04-14 08:44
@horar The console tool also had this issue... :-/

**Comment by horar** [comment] 2018-03-03 16:09
Hi could you please try [this script](https://github.com/horar/vpnc-scripts/blob/master/vpnc-script-win.js)? ... replace/rename the local one. Thanks.

**Comment by bodhidogma** [comment] 2018-04-02 13:59
I had a similar issue, tried the script from @horar and the routes are now added correctly (used openconnect-gui-1.5.2-win23)

**Comment by horar** [comment] 2018-04-04 19:38
@bodhidogma thanks of update.

This should be fixed in oc-gui v1.5.3 (fixed by #190)

**Closed by horar** 2018-04-04 19:38 UTC
Labels: bug, component:vpnc-script, os:MinGW
