### ISSUE TITLE
losing saved passwords

### ISSUE THREAD

**Issue by ahmedmg** [openconnect/openconnect-gui#42] opened 2015-06-07 17:27 UTC
one profile seems to be losing password after saving it with batch mode selected it works for a couple of times then it asks for password again as it was not saved

**Comment by nmav** [comment] 2015-06-08 08:27
Could you provide a step by step way to reproduce the issue?

**Comment by ahmedmg** [comment] 2015-06-09 01:42
Actually I can't reproduce that now it's fixed somehow! I was having two profiles with different servers and the same user/pass and now I have different account user/pass for each profile and it's not losing saved passwords anymore may be that's the problem, duplicate passwords?

**Comment by nmav** [comment] 2015-07-17 13:03
No idea. I'm closing it now, but feel free to reopen if there is a reproducer.

**Closed by nmav** 2015-07-17 13:03 UTC

**Comment by chk-mk** [comment] 2017-11-05 23:56
I'm getting this issue, running 1.5.2. The steps are:

1. Connect (prompt for password appears)
2. Disconnect
3. Connect (no prompt, works)
4. Disconnect
5. Connect (prompt appears again)

The log shows this:

2017-11-06 10:43:36 | 107c | Authentication failed in batch mode, retrying with batch mode disabled

It seems that the service provider semi-randomly rejects connections. They also have a connection time limit, guaranteeing that the issue eventually occurs. Their support team has not helped with any of my requests.

So it looks like the behavior in batch mode is to fall back to interactive on certain error conditions. Is there some way to lock it into batch mode, and to retry indefinitely? Ideally it should have a delay that doubles each retry up to some limit like an hour.

**Comment by horar** [comment] 2017-11-06 08:55
@chk-mk I guess, I face this few times in past, it's already reported in #142
