### ISSUE TITLE
How to connect Cisco vpn

### ISSUE THREAD

**Issue by marcoz90** [openconnect/openconnect-gui#194] opened 2017-08-30 14:48 UTC
Hi guys,
I'm using OpenConnect-GUI 1.5.2 on Windows 7 Pro 64Bit.
I'm trying to configure a Cisco vpn with the following data:
- Gateway
- GroupName
- GroupPassword
- UserName
- UserPassword

Reading the FAQ I've inserted "https://**Gateway**/**GroupName**" in the "Gateway" field
and my **UserName** in the "Username" field,
but I cannot find where to insert the **GroupPassword** and **UserPassword**.
If I click on "Connect" I'm not prompted for any password,
but I'm sure the vpn works cause I'm able to connect from other clients.

Could you please help me with the configuration?
Thank you,
Marco.

**Comment by marcoz90** [comment] 2017-09-01 08:27
Hi @horar,
by inserting only the ip nothing happens when I click on "connect".
Do you think there may be something to allow in the Firewall side?
Consider that the same vpn works using a different software.

Thank you,
Marco.

**Comment by horar** [comment] 2017-09-01 12:44
hmm, let start with some standard questions:
1. do you see something weird in application log?
2. did you try console client? (is optional part of GUI installer)

**Comment by deeporist** [comment] 2017-09-10 09:53
dude, not your fault, i think 1.5.2 has bug, my tap can not connect the network after the id auth. My os is win 8.1 x64, 1.5.1 works well with it.

**Comment by horar** [comment] 2017-09-10 14:35
@deeporist hi, can you share with us the log from 1.5.2? It may help to find the reason... the problem is with GUI only or with console as well? Thanks.

**Comment by deeporist** [comment] 2017-09-11 04:57
@horar sorry, i didn't preserved the log of 1.5.2. I think the problem is with console because i tried it too and failed with no errors in the log. my server version is ocserv 0.11.6 works on the debian. I noticed the tap adaptor in windows showed "unrecognized network" after "try id authentication".

**Comment by horar** [comment] 2017-09-11 10:07
@deeporist yes, the console application log only to output; could you please try it again; may be you can try with previous version of [vpnc-script](http://git.infradead.org/users/dwmw2/vpnc-scripts.git/blob_plain/HEAD:/vpnc-script-win.js). This script solve e.g. localised interface names etc.
The last release 1.5.2 is working fine, just few people complain about troubles. We should find the reason for it. Thanks in advance.

**Comment by deeporist** [comment] 2017-09-12 08:17
@horar here is the log with 1.5.2
###################################################
H:\openconnect-gui-1.5.2-win32>openconnect.exe -v -c \PATH\user-cert.pem -k \PATH\user-key.pem --cafile=\PATH\ca-cert.pem SERVER-IP:PORT
POST https://SERVER-IP:PORT/
Attempting to connect to server SERVER-IP:PORT
Connected to SERVER-IP:PORT
Using certificate file \PATH\user-cert.pem
Using private key file \PATH\user-key.pem
Using client certificate 'NAME'
SSL negotiation with SERVER-IP
Connected to HTTPS on SERVER-IP
Got HTTP response: HTTP/1.1 200 OK
Connection: Keep-Alive
Content-Type: text/xml
Content-Length: 224
X-Transcend-Version: 1
Set-Cookie: webvpncontext=9OJ+4wsR4WVoCUBTP5Jf6YpE8YcOFo7ay5USAHaTzs8=; Secure
Set-Cookie: webvpn=<elided>; Secure
Set-Cookie: webvpnc=; expires=Thu, 01 Jan 1970 22:00:00 GMT; path=/; Secure
Set-Cookie: webvpnc=bu:/&p:t&iu:1/&sh:D36644D92A90024187E992044F07B7E3C328692E; path=/; Secure
HTTP body length:  (224)
XML POST enabled
SSL negotiation with SERVER-IP
Connected to HTTPS on SERVER-IP
Got CONNECT response: HTTP/1.1 200 CONNECTED
X-CSTP-Version: 1
X-CSTP-Server-Name: ocserv 0.11.6
X-CSTP-Hostname: localhost
X-CSTP-DPD: 20
X-CSTP-Default-Domain: NAME.com
X-CSTP-Address: 10.168.250.123
X-CSTP-Netmask: 255.255.255.0
X-CSTP-DNS: 8.8.8.8
X-CSTP-DNS: 8.8.4.4
X-CSTP-Tunnel-All-DNS: true
X-CSTP-Keepalive: 60
X-CSTP-Idle-Timeout: none
X-CSTP-Smartcard-Removal-Disconnect: true
X-CSTP-Rekey-Time: 172824
X-CSTP-Rekey-Method: ssl
X-CSTP-Session-Timeout: none
X-CSTP-Disconnected-Timeout: none
X-CSTP-Keep: true
X-CSTP-TCP-Keepalive: true
X-CSTP-License: accept
X-DTLS-DPD: 20
X-DTLS-Port: PORT
X-DTLS-Rekey-Time: 172834
X-DTLS-Rekey-Method: ssl
X-DTLS-Keepalive: 60
X-DTLS-App-ID: f5711dcd68e3a09f829516148ddcbbd46306c94026eeac5c282b660045fafc4b
X-DTLS-CipherSuite: PSK-NEGOTIATE
X-CSTP-Base-MTU: 1406
X-CSTP-MTU: 1340
X-CSTP-Banner: Hasa Digga Eebowai
CSTP connected. DPD 20, Keepalive 60
CSTP Ciphersuite: (TLS1.2)-(ECDHE-RSA-SECP256R1)-(AES-256-GCM)
DTLS option X-DTLS-DPD : 20
DTLS option X-DTLS-Port : PORT
DTLS option X-DTLS-Rekey-Time : 172834
DTLS option X-DTLS-Rekey-Method : ssl
DTLS option X-DTLS-Keepalive : 60
DTLS option X-DTLS-App-ID : f5711dcd68e3a09f829516148ddcbbd46306c94026eeac5c282b660045fafc4b
DTLS option X-DTLS-CipherSuite : PSK-NEGOTIATE
DTLS initialised. DPD 20, Keepalive 60
Connected as 10.168.250.123, using SSL
Established DTLS connection (using GnuTLS). Ciphersuite (DTLS1.2)-(PSK)-(AES-256-GCM).
Initiating IPv4 MTU detection (min=670, max=1340)
No change in MTU after detection (was 1340)
Microsoft (R) Windows Script Host Version 5.8
Copyright (C) Microsoft Corporation. All rights reserved.

Microsoft (R) Windows Script Host Version 5.8
Copyright (C) Microsoft Corporation. All rights reserved.

<<-- [EXEC] route print
===================================================================
Interface List
 13...00 ff bd 5f 33 d5 ......TAP-Windows Adapter V9
  3...8c 89 a5 32 2a 00 ......Qualcomm Atheros AR8131 PCI-E XXXXX (NDIS 6.30)
  1...........................Software Loopback Interface 1
===================================================================

IPv4 Route Table
===================================================================
Active Routes:
Network Destination        Netmask          Gateway       Interface  Metric
          0.0.0.0          0.0.0.0      192.168.1.1      192.168.1.5     20
     10.168.250.0    255.255.255.0         On-link    10.168.250.123    257
   10.168.250.123  255.255.255.255         On-link    10.168.250.123    257
   10.168.250.255  255.255.255.255         On-link    10.168.250.123    257
        127.0.0.0        255.0.0.0         On-link         127.0.0.1    306
        127.0.0.1  255.255.255.255         On-link         127.0.0.1    306
  127.255.255.255  255.255.255.255         On-link         127.0.0.1    306
      192.168.1.0    255.255.255.0         On-link       192.168.1.5    276
      192.168.1.5  255.255.255.255         On-link       192.168.1.5    276
    192.168.1.255  255.255.255.255         On-link       192.168.1.5    276
        224.0.0.0        240.0.0.0         On-link         127.0.0.1    306
        224.0.0.0        240.0.0.0         On-link    10.168.250.123    257
        224.0.0.0        240.0.0.0         On-link       192.168.1.5    276
  255.255.255.255  255.255.255.255         On-link         127.0.0.1    306
  255.255.255.255  255.255.255.255         On-link    10.168.250.123    257
  255.255.255.255  255.255.255.255         On-link       192.168.1.5    276
===================================================================
Persistent Routes:
  Network Address          Netmask  Gateway Address  Metric

===================================================================

IPv6 Route Table
===================================================================
Active Routes:
 If Metric Network Destination      Gateway
  1    306 ::1/128                  On-link
 13    276 fe80::/64                On-link
  3    276 fe80::/64                On-link
 13    276 fe80::b862:6f70:5102:2819/128
                                    On-link
  3    276 fe80::c4cd:4448:789:52f3/128
                                    On-link
  1    306 ff00::/8                 On-link
 13    276 ff00::/8                 On-link
  3    276 ff00::/8                 On-link
===================================================================
Persistent Routes:
  None

-->> (exitCode: 0)
Default Gateway:192.168.1.1
VPN Gateway: SERVER-IP
Internal Address: 10.168.250.123
Internal Netmask: 255.255.255.0
Internal Gateway: 10.168.250.1
Interface idx: "13" ("ETHERNET 2")
<<-- [EXEC] route add SERVER-IP mask 255.255.255.255 192.168.1.1
 OK!

-->> (exitCode: 0)
MTU: 1340
<<-- [EXEC] netsh interface ipv4 set subinterface "13" mtu=1340 store=active
Ok.


-->> (exitCode: 0)
Configuring "13" interface for Legacy IP...
<<-- [EXEC] netsh interface ip set interface "13" metric=1
Ok.


-->> (exitCode: 0)
<<-- [EXEC] netsh interface ip set address "13" static 10.168.250.123 255.255.255.0


-->> (exitCode: 0)
<<-- [EXEC] netsh interface ip add dns "13" 8.8.8.8 index=1
The object is already in the list.



-->> (exitCode: 1)
<<-- [EXEC] netsh interface ip add dns "13" 8.8.4.4 index=2
The object is already in the list.



-->> (exitCode: 1)
done.
Configuring Legacy IP networks:
Route configuration done.
--------------------- BANNER ---------------------
OK
------------------- BANNER end -------------------

###################################################

**Comment by horar** [comment] 2018-03-02 20:10
Will by fixed by #190, closing as duplicate.

**Closed by horar** 2018-03-02 20:10 UTC
Labels: question
