### ISSUE TITLE
Endless authentication loop in Juniper batch mode

### ISSUE THREAD

**Issue by dlenski** [openconnect/openconnect-gui#173] opened 2017-06-05 21:17 UTC
### Description of the Issue

I'm trying to create a Juniper connection profile and use it in "Batch mode" so that it saves passwords and authentication realm.

The initial connection works successfully, but subsequent attempts in "Batch mode" get stuck in an endless loop, which repeats until the server temporarily locks out the account:

```
2017-06-05 15:00:04 | 2e60 | GET https://x.y.com/dana-na/auth/url_default/welcome.cgi
2017-06-05 15:00:04 | 2e60 | SSL negotiation with x.y.com
2017-06-05 15:00:04 | 2e60 | Connected to HTTPS on x.y.com
2017-06-05 15:00:04 | 2e60 | Got HTTP response: HTTP/1.1 200 OK
2017-06-05 15:00:04 | 2e60 | Content-Type: text/html; charset=utf-8
2017-06-05 15:00:04 | 2e60 | Date: Tue, 06 Jun 2017 01:46:52 GMT
2017-06-05 15:00:04 | 2e60 | Connection: close
2017-06-05 15:00:04 | 2e60 | Pragma: no-cache
2017-06-05 15:00:04 | 2e60 | Cache-Control: no-store
2017-06-05 15:00:04 | 2e60 | Expires: -1
2017-06-05 15:00:04 | 2e60 | HTTP body http 1.0 (-1)
2017-06-05 15:00:04 | 2e60 | SSL socket closed uncleanly
2017-06-05 15:00:04 | 2e60 | frmLogin
2017-06-05 15:00:04 | 2e60 | frmLogin
2017-06-05 15:00:04 | 2e60 | Select form: realm
2017-06-05 15:00:04 | 2e60 | unknown type 4
2017-06-05 15:00:04 | 2e60 | Text form: username
2017-06-05 15:00:04 | 2e60 | Password form: password
2017-06-05 15:00:04 | 2e60 | unknown type 4
2017-06-05 15:00:04 | 2e60 | POST https://x.y.com/dana-na/auth/url_default/login.cgi
2017-06-05 15:00:04 | 2e60 | SSL negotiation with x.y.com
2017-06-05 15:00:04 | 2e60 | Connected to HTTPS on x.y.com
2017-06-05 15:00:04 | 2e60 | Got HTTP response: HTTP/1.1 302 Moved
```

### Specifications
- **Version**: 1.5.1
- **Platform**: Windows Server 2012, 64-bit

### Analysis with mitmproxy

I ran the connection through `mitmproxy`, and here's the problem: for some bizarre reason it is trying on subsequent attempts to log me in using a password of `https://` instead of the actual saved password value:

```
realm=FOO&tz_offset=&username=dlenski&password=https%3a%2f%2f&btnSubmit=Sign%20In
```

Not sure where this errant password value is coming from…

**Comment by horar** [comment] 2018-01-15 02:23
Thanks for the report.
Yes, there is a problem with batch-mode & saved-password.
Will look at it (duplicate of #142)

**Closed by horar** 2018-01-15 02:23 UTC
