### ISSUE TITLE
Cannot specify different interface

### ISSUE THREAD

**Issue by chemik3** [openconnect/openconnect-gui#103] opened 2016-03-25 17:25 UTC
I cannot connect to VPN when i use command line oppenconnect.exe and specify different TAP interface via parameter --interface="TUN_SEC". I receive error message:

Ignoring non-matching TAP interface "TUN"
 Set up tun device failed

and word "TUN" is name of first TAP adapter in my system. When i change name of interface is also changed on output in the error message. Openconnect probably use first TAP interface in the windows and ignoring parametr --interface= . I have 2 TAP interfaces because i want to run 2 instances openconnect  and connect simultaneous to 2 different VPN networks. Thansk for help.

**Comment by horar** [comment] 2016-08-28 18:55
Hi @chemik3 , just tried something like: openconnect.exe --interface "Ethernet 2" https:/xxxxxxxxx
It looks OK for me, I was connected (Openconnect-gui 1.4; openconnect v7.06).
Btw. did you start openconnect in console running in admin mode?

**Comment by horar** [comment] 2016-09-12 20:54
@chemik3 hi, is this still valid? Thanks.

**Comment by horar** [comment] 2017-04-09 23:04
No more comments, closing.
If the problem is still valid, please initiate discussion in [openconnect mailing list](http://lists.infradead.org/mailman/listinfo/openconnect-devel). This project is only about GUI part.

**Closed by horar** 2017-04-09 23:04 UTC
Labels: component:openconnect
