### ISSUE TITLE
How do I specify the user/password and OTP RSA info?

### ISSUE THREAD

**Issue by Toppertje** [openconnect/openconnect-gui#175] opened 2017-06-15 12:46 UTC
### Description of the Issue
I cannot get the openconnect-gui to display the uid/pwd box. The username/password box doesn't show up. Here's the log:
2017-06-15 14:53:10 |  97c | POST https://vpn1.klm.com/
2017-06-15 14:53:10 |  97c | Attempting to connect to server 171.21.80.215:443
2017-06-15 14:53:10 |  97c | Connected to 171.21.80.215:443
2017-06-15 14:53:10 |  97c | There was a non-CA certificate in the trusted list: OU=Copyright (c) 1997 Microsoft Corp.,OU=Microsoft Corporation,CN=Microsoft Root Authority.
2017-06-15 14:53:10 |  97c | There was a non-CA certificate in the trusted list: C=US,O=MSFT,CN=Microsoft Authenticode(tm) Root Authority.
2017-06-15 14:53:10 |  97c | There was a non-CA certificate in the trusted list: CN=Root Agency.
2017-06-15 14:53:10 |  97c | SSL negotiation with vpn1.klm.com
2017-06-15 14:53:11 |  97c | Connected to HTTPS on vpn1.klm.com
**2017-06-15 14:53:11 |  97c | Got HTTP response: HTTP/1.1 200 OK
2017-06-15 14:53:11 |  97c | Content-Type: text/html; charset=utf-8
2017-06-15 14:53:11 |  97c | Transfer-Encoding: chunked
2017-06-15 14:53:11 |  97c | Cache-Control: no-cache
2017-06-15 14:53:11 |  97c | Pragma: no-cache
2017-06-15 14:53:11 |  97c | Connection: Keep-Alive
2017-06-15 14:53:11 |  97c | Date: Thu, 15 Jun 2017 12:53:11 GMT
2017-06-15 14:53:11 |  97c | X-Frame-Options: SAMEORIGIN
2017-06-15 14:53:11 |  97c | X-Aggregate-Auth: 1
2017-06-15 14:53:11 |  97c | HTTP body chunked (-2)
**2017-06-15 14:53:11 |  97c | Server requested SSL client certificate; none was configured
2017-06-15 14:53:11 |  97c | POST https://vpn1.klm.com/
2017-06-15 14:53:11 |  97c | Got HTTP response: HTTP/1.1 200 OK
2017-06-15 14:53:11 |  97c | Content-Type: text/html; charset=utf-8
2017-06-15 14:53:11 |  97c | Transfer-Encoding: chunked
2017-06-15 14:53:11 |  97c | Cache-Control: no-cache
2017-06-15 14:53:11 |  97c | Pragma: no-cache
2017-06-15 14:53:11 |  97c | Connection: Keep-Alive
2017-06-15 14:53:11 |  97c | Date: Thu, 15 Jun 2017 12:53:11 GMT
2017-06-15 14:53:11 |  97c | X-Frame-Options: SAMEORIGIN
2017-06-15 14:53:11 |  97c | X-Aggregate-Auth: 1
2017-06-15 14:53:11 |  97c | HTTP body chunked (-2)
2017-06-15 14:53:11 |  97c | XML POST enabled
**2017-06-15 14:53:11 |  97c | Please enter your username and password.
2017-06-15 14:53:11 |  97c | Certificate Validation Failure
2017-06-15 14:53:11 |  97c | Authentication error; cannot obtain cookie
2017-06-15 14:53:11 |  c90 | Disconnected

In the log I see a HTTP/1.1 200 OK, some errorless lines below I see 'Please enter your username and password.' but that doesn't show up on my screen.

The connection is working in anyconnect, without specifying a user certificate. This is the anyconnect log:
[15-6-2017 15:07:46] Contacting vpn1.klm.com.
[15-6-2017 15:07:47] No valid certificates available for authentication.
[15-6-2017 15:07:47] Awaiting user input.
[15-6-2017 15:07:53] User credentials entered.
[15-6-2017 15:07:55] Login failed.
[15-6-2017 15:07:56] User credentials prompt cancelled.

I have the following combination that I need to provide to my vpn server:
- server:  vpn1.klm.com
- username: ***
- password: ***
- Group: VPN4TP-ANYCONNECT
- OTP STOKEN (RSA) starts with 1815

I see the groupname option on the openconnect form has no edit control, only the label.

Please let me know what I am missing here. Happy to work on the documentation =)

### Specifications
- **Version**: 1.51, build 11.02.2017
- **Platform**: Windows 2008R2 64-bit (alltough it installs in c:\program files (x86))

### Steps to Reproduce the Issue
1. open openconnect-gui
2. fill in the server, hit enter, but no uid/pwd prompt

### Expected Behavior
uid/pwd box shows up

### Actual Behavior
uid/pwd box does not shows up

### Other Information
N.a.

**Comment by horar** [comment] 2017-06-15 13:01
hi @Toppertje 
1. in many cases the openconnect works fine in way that you set the vpn-gateway name only and user is asked for other requested data (username, password, group etc.) when needed
2. when you need to define specific more complex scenario, you can open existing profile or create new one via "new profile (advanced)" action and define the setup yourself
3. about OTP, there is a combo box with edit box where to enter OTP (look at [screen shot no. 4](https://openconnect.github.io/openconnect-gui/))

**Comment by Toppertje** [comment] 2017-06-15 13:24
Hi Horar, just opened a simple connection, only specified the server (https://vpn1.klm.com) but same results, no pop  up to fill in other details ... I do see the request in the log, but not in the screen. Any other ideas?

**Comment by horar** [comment] 2017-06-15 13:39
hmm, I will take a look...

**Comment by Toppertje** [comment] 2017-06-15 13:40
Thanks, if you need more details, let me know. I am on holiday till tuesday though ... =)

**Comment by horar** [comment] 2017-08-06 17:36
ok, the problem was that we preliminary stop the connection; should be fixed - please try with v1.5.2  (will come in next few days)

**Closed** 2017-08-06 18:25 UTC
Labels: bug, component:gui

**Comment by kangzj** [comment] 2017-09-28 21:47
Hey horar, thanks for your works.
But this happens to em on 1.5.2 too. It'll be great if you can have a look.

2017-09-29 10:45:51 | 48a0 | POST https://vpn.XX.nz:4343/
2017-09-29 10:45:51 | 48a0 | Attempting to connect to server 52.65.47.3:4343
2017-09-29 10:45:51 | 48a0 | Connected to 52.65.47.3:4343
2017-09-29 10:45:51 | 48a0 | There was a non-CA certificate in the trusted list: OU=Copyright (c) 1997 Microsoft Corp.,OU=Microsoft Corporation,CN=Microsoft Root Authority.
2017-09-29 10:45:51 | 48a0 | There was a non-CA certificate in the trusted list: C=US,O=MSFT,CN=Microsoft Authenticode(tm) Root Authority.
2017-09-29 10:45:51 | 48a0 | There was a non-CA certificate in the trusted list: CN=Root Agency.
2017-09-29 10:45:51 | 48a0 | SSL negotiation with vpn.XX.nz
2017-09-29 10:45:51 | 48a0 | Connected to HTTPS on vpn.XX.nz
2017-09-29 10:45:51 | 48a0 | Got HTTP response: HTTP/1.1 200 OK
2017-09-29 10:45:51 | 48a0 | Set-Cookie: webvpncontext=; expires=Thu, 01 Jan 1970 22:00:00 GMT; path=/; Secure
2017-09-29 10:45:51 | 48a0 | Content-Type: text/xml
2017-09-29 10:45:51 | 48a0 | Content-Length: 306
2017-09-29 10:45:51 | 48a0 | X-Transcend-Version: 1
2017-09-29 10:45:51 | 48a0 | HTTP body length:  (306)
2017-09-29 10:45:51 | 48a0 | XML POST enabled
2017-09-29 10:45:51 | 48a0 | Please enter your username.
2017-09-29 10:45:51 | 48a0 | Text form: username
2017-09-29 10:45:51 | 48a0 | Authentication failed in batch mode, retrying with batch mode disabled
2017-09-29 10:45:51 | 48a0 | POST https://vpn.XX.nz:4343/auth
2017-09-29 10:45:51 | 48a0 | Attempting to connect to server 52.65.47.3:4343
2017-09-29 10:45:51 | 48a0 | Connected to 52.65.47.3:4343
2017-09-29 10:45:51 | 48a0 | SSL negotiation with vpn.XX.nz
2017-09-29 10:45:51 | 48a0 | Connected to HTTPS on vpn.XX.nz
2017-09-29 10:45:51 | 48a0 | Got HTTP response: HTTP/1.1 200 OK
2017-09-29 10:45:51 | 48a0 | Set-Cookie: webvpncontext=; expires=Thu, 01 Jan 1970 22:00:00 GMT; path=/; Secure
2017-09-29 10:45:51 | 48a0 | Content-Type: text/xml
2017-09-29 10:45:51 | 48a0 | Content-Length: 306
2017-09-29 10:45:51 | 48a0 | X-Transcend-Version: 1
2017-09-29 10:45:51 | 48a0 | HTTP body length:  (306)
2017-09-29 10:45:51 | 48a0 | XML POST enabled
2017-09-29 10:45:51 | 48a0 | Please enter your username.
2017-09-29 10:45:51 | 48a0 | Text form: username
2017-09-29 10:45:51 | 48a0 | Authentication failed in batch mode, retrying with batch mode disabled
2017-09-29 10:45:51 | 48a0 | POST https://vpn.XX.nz:4343/auth
2017-09-29 10:45:51 | 48a0 | Attempting to connect to server 52.65.47.3:4343
2017-09-29 10:45:51 | 48a0 | Connected to 52.65.47.3:4343
2017-09-29 10:45:51 | 48a0 | SSL negotiation with vpn.XX.nz
2017-09-29 10:45:52 | 48a0 | Connected to HTTPS on vpn.XX.nz
2017-09-29 10:45:52 | 48a0 | Got HTTP response: HTTP/1.1 200 OK
2017-09-29 10:45:52 | 48a0 | Set-Cookie: webvpncontext=; expires=Thu, 01 Jan 1970 22:00:00 GMT; path=/; Secure
2017-09-29 10:45:52 | 48a0 | Content-Type: text/xml
2017-09-29 10:45:52 | 48a0 | Content-Length: 306
2017-09-29 10:45:52 | 48a0 | X-Transcend-Version: 1
2017-09-29 10:45:52 | 48a0 | HTTP body length:  (306)
2017-09-29 10:45:52 | 48a0 | XML POST enabled
2017-09-29 10:45:52 | 48a0 | Please enter your username.
2017-09-29 10:45:52 | 48a0 | Text form: username
2017-09-29 10:45:52 | 24d8 | Disconnected

**Comment by horar** [comment] 2017-09-28 22:24
@kangzj hi, the problem is you can log into vpn in interactive mode or do you try batch mode? Looks like the error in batch mode, could you please try disable this mode in profile and try it again?

**Comment by gedumas** [comment] 2018-10-19 08:54
@horar I have the same issue with v 1.5.1-dirty 
Installed via: brew cask install openconnect-gui # gui
![skjermbilde 2018-10-19 kl 10 22 48](https://user-images.githubusercontent.com/30437464/47206712-9d6dd000-d389-11e8-889b-2256324d1972.png)
here is the log:
2018-10-19 10:21:55 | 7fffa6633380 | Disconnected
2018-10-19 10:22:35 | 7000007f3000 | POST https://...
2018-10-19 10:22:35 | 7000007f3000 | Attempting to connect to server ...
2018-10-19 10:22:35 | 7000007f3000 | Connected to ...
2018-10-19 10:22:35 | 7000007f3000 | SSL negotiation with anyconnect.netcompany.com
2018-10-19 10:22:35 | 7000007f3000 | Server certificate verify failed: signer not found
2018-10-19 10:22:35 | 7000007f3000 | Connected to HTTPS on anyconnect.netcompany.com
2018-10-19 10:22:35 | 7000007f3000 | Got HTTP response: HTTP/1.1 200 OK
2018-10-19 10:22:35 | 7000007f3000 | Content-Type: text/html; charset=utf-8
2018-10-19 10:22:35 | 7000007f3000 | Transfer-Encoding: chunked
2018-10-19 10:22:35 | 7000007f3000 | Cache-Control: no-cache
2018-10-19 10:22:35 | 7000007f3000 | Pragma: no-cache
2018-10-19 10:22:35 | 7000007f3000 | Connection: Keep-Alive
2018-10-19 10:22:35 | 7000007f3000 | Date: Fri, 19 Oct 2018 08:22:35 GMT
2018-10-19 10:22:35 | 7000007f3000 | X-Frame-Options: SAMEORIGIN
2018-10-19 10:22:35 | 7000007f3000 | X-Aggregate-Auth: 1
2018-10-19 10:22:35 | 7000007f3000 | HTTP body chunked (-2)
2018-10-19 10:22:35 | 7000007f3000 | Server requested SSL client certificate; none was configured
2018-10-19 10:22:35 | 7000007f3000 | POST ...
2018-10-19 10:22:35 | 7000007f3000 | Got HTTP response: HTTP/1.1 200 OK
2018-10-19 10:22:35 | 7000007f3000 | Content-Type: text/html; charset=utf-8
2018-10-19 10:22:35 | 7000007f3000 | Transfer-Encoding: chunked
2018-10-19 10:22:35 | 7000007f3000 | Cache-Control: no-cache
2018-10-19 10:22:35 | 7000007f3000 | Pragma: no-cache
2018-10-19 10:22:35 | 7000007f3000 | Connection: Keep-Alive
2018-10-19 10:22:35 | 7000007f3000 | Date: Fri, 19 Oct 2018 08:22:35 GMT
2018-10-19 10:22:35 | 7000007f3000 | X-Frame-Options: SAMEORIGIN
2018-10-19 10:22:35 | 7000007f3000 | X-Aggregate-Auth: 1
2018-10-19 10:22:35 | 7000007f3000 | HTTP body chunked (-2)
2018-10-19 10:22:35 | 7000007f3000 | XML POST enabled
2018-10-19 10:22:35 | 7000007f3000 | Please enter your username and password.
2018-10-19 10:22:35 | 7000007f3000 | Certificate Validation Failure
2018-10-19 10:22:35 | 7000007f3000 | Authentication error; cannot obtain cookie
2018-10-19 10:22:35 | 7fffa6633380 | Disconnected

VIA TERMINAL:
:~ gedisi$ sudo openconnect https://anyconnect.netcompany.com/
Password:
POST 
Connected to 
SSL negotiation with 
Connected to HTTPS on 
Server requested SSL client certificate; none was configured
POST 
XML POST enabled
Certificate Validation Failure
Please enter your username and password.
GROUP: [Default]:Default
POST https://anyconnect.netcompany.com/
Server requested SSL client certificate; none was configured
POST 
XML POST enabled
Certificate Validation Failure
Please enter your username and password.
POST 
Certificate Validation Failure
Please enter your username and password.
Failed to obtain WebVPN cookie

thank you for your tips!
