### ISSUE TITLE
Loading an private key with password freezes the UI

### ISSUE THREAD

**Issue by sergiomb2** [openconnect/openconnect-gui#244] opened 2018-07-05 10:56 UTC
### Specifications
- **Version**:  v1.5.3 
- **Platform**:  windows 10 

### Steps to Reproduce the Issue

1. prepare ca.crt , user_cert.crt and user_private.key 
2. install openconnect-gui on windows 10 and add profile 
3. when load private key , if private key have password the gui freeze 

### Expected Behavior

ask password and not hang gui

### Actual Behavior

hang gui

### Other Information

After remove the passphrase with: openssl rsa -in server.key -out server-new.key and use the private key without passphrase works perfectly

**Comment by horar** [comment] 2018-07-05 19:58
Thanks for report. Fix is on the way - anyway, this is already reported - closing this as duplicate of #128

**Closed by horar** 2018-07-05 19:58 UTC

**Comment by sergiomb2** [comment] 2018-07-06 11:01
Hello
"on the way" means what ? the other bug was opened in 2016 , and this is a **big show stopper** , I waste lots a time wonder what happens , and almost give up on openconnect solution. At leat it should be advertise that we should use a very insecure configuration which means private key without password
