### ISSUE TITLE
Error setting up the TUN device

### ISSUE THREAD

**Issue by Biggizen** [openconnect/openconnect-gui#140] opened 2016-09-25 20:55 UTC
Hello,

I get an error, when I try to establish a VPN-connection. 

Here is what the log-file says:

2016-09-25 22:11 Setting proxy to: :@127.0.0.1:8118
2016-09-25 22:11 POST https://vpn.uni-muenster.de/
2016-09-25 22:11 Attempting to connect to server 127.0.0.1:8118
2016-09-25 22:11 Requesting HTTP proxy connection to vpn.uni-muenster.de:443
2016-09-25 22:11 Got HTTP response: HTTP/1.1 200 Connection established
2016-09-25 22:11 SSL negotiation with vpn.uni-muenster.de
2016-09-25 22:11 Connected to HTTPS on vpn.uni-muenster.de
2016-09-25 22:11 Got HTTP response: HTTP/1.1 200 OK
2016-09-25 22:11 Content-Type: text/html; charset=utf-8
2016-09-25 22:11 Transfer-Encoding: chunked
2016-09-25 22:11 Cache-Control: no-cache
2016-09-25 22:11 Pragma: no-cache
2016-09-25 22:11 Connection: Keep-Alive
2016-09-25 22:11 Date: Sun, 25 Sep 2016 20:12:47 GMT
2016-09-25 22:11 X-Frame-Options: SAMEORIGIN
2016-09-25 22:11 X-Aggregate-Auth: 1
2016-09-25 22:11 HTTP body chunked (-2)
2016-09-25 22:11 XML POST enabled
2016-09-25 22:11 Bitte geben Sie Ihre zentrale Nutzerkennung und Ihr Netzzugangspasswort ein.
2016-09-25 22:11 Text form: username
2016-09-25 22:11 Password form: password
2016-09-25 22:11 POST https://vpn.uni-muenster.de/
2016-09-25 22:11 Got HTTP response: HTTP/1.1 200 OK
2016-09-25 22:11 Content-Type: text/html; charset=utf-8
2016-09-25 22:11 Transfer-Encoding: chunked
2016-09-25 22:11 Cache-Control: no-cache
2016-09-25 22:11 Pragma: no-cache
2016-09-25 22:11 Connection: Keep-Alive
2016-09-25 22:11 Date: Sun, 25 Sep 2016 20:12:54 GMT
2016-09-25 22:11 X-Frame-Options: SAMEORIGIN
2016-09-25 22:11 X-Aggregate-Auth: 1
2016-09-25 22:11 HTTP body chunked (-2)
2016-09-25 22:11 Got CONNECT response: HTTP/1.1 200 OK
2016-09-25 22:11 X-CSTP-Version: 1
2016-09-25 22:11 X-CSTP-Protocol: Copyright (c) 2004 Cisco Systems, Inc.
2016-09-25 22:11 X-CSTP-Address: 10.68.1.23
2016-09-25 22:11 X-CSTP-Netmask: 255.255.240.0
2016-09-25 22:11 X-CSTP-Hostname: ASA-WWU.uni-muenster.de
2016-09-25 22:11 X-CSTP-DNS: 128.176.0.12
2016-09-25 22:11 X-CSTP-DNS: 128.176.0.13
2016-09-25 22:11 X-CSTP-Lease-Duration: 1209600
2016-09-25 22:11 X-CSTP-Session-Timeout: none
2016-09-25 22:11 X-CSTP-Idle-Timeout: 1800
2016-09-25 22:11 X-CSTP-Disconnected-Timeout: 1800
2016-09-25 22:11 X-CSTP-Default-Domain: uni-muenster.de
2016-09-25 22:11 X-CSTP-Split-Exclude: 0.0.0.0/255.255.255.255
2016-09-25 22:11 X-CSTP-Split-DNS: uni-muenster.de
2016-09-25 22:11 X-CSTP-Keep: true
2016-09-25 22:11 X-CSTP-Tunnel-All-DNS: true
2016-09-25 22:11 X-CSTP-DPD: 30
2016-09-25 22:11 X-CSTP-Keepalive: 20
2016-09-25 22:11 X-CSTP-MSIE-Proxy-Lockdown: true
2016-09-25 22:11 X-CSTP-Smartcard-Removal-Disconnect: true
2016-09-25 22:11 X-DTLS-Session-ID: E72A917987EA107C5C67BE334903978B6E76F8053B8BA4644130C1D16A41969A
2016-09-25 22:11 X-DTLS-Port: 443
2016-09-25 22:11 X-DTLS-Keepalive: 20
2016-09-25 22:11 X-DTLS-DPD: 30
2016-09-25 22:11 X-CSTP-MTU: 1406
2016-09-25 22:11 X-DTLS-CipherSuite: AES256-SHA
2016-09-25 22:11 X-CSTP-Routing-Filtering-Ignore: false
2016-09-25 22:11 X-CSTP-Quarantine: false
2016-09-25 22:11 X-CSTP-Disable-Always-On-VPN: false
2016-09-25 22:11 X-CSTP-Client-Bypass-Protocol: false
2016-09-25 22:11 X-CSTP-TCP-Keepalive: true
2016-09-25 22:11 X-CSTP-Post-Auth-XML: <elided>
2016-09-25 22:11 CSTP connected. DPD 30, Keepalive 20
2016-09-25 22:11 CSTP Ciphersuite: (TLS1.0)-(RSA)-(AES-256-CBC)-(SHA1)
2016-09-25 22:11 Failed to open \.\Global{93D2F4AB-5E9D-4B53-ADD6-7E93B5132818}.tap
2016-09-25 22:11 Error setting up the TUN device
2016-09-25 22:11 Disconnected

The proxy setting (127.0.0.1:8118) is set because of my local software-proxy "Privoxy". I allready tried to connect without the proxy, but it makes no difference - same error. I don't know what the "{93D2F4AB-5E9D-4B53-ADD6-7E93B5132818}.tap" is. Is it a file? There is no file with this name on my HDD. 

Yesterday the connection established without a problem, today it doesn't work. I cannot remember, that I have done something in the meanwhile, which could cause problems whith a VPN-connection, but I cannot exclude that, because I am really no expert for VPN-connections and errors belonging to it, sorry.

Does someone know how to solve this Problem? Thank you!

I use version 1.4 on Windows 10 Enterprise N 2016 LTSB (x64).

**Comment by horar** [comment] 2017-02-05 22:45
Could you plese try uninstall TAP drivers (in Control panel) and reinstall openconnect-gui?
If the problem still exists, please try console openconnect.exe to identify if the problem is in console tool or in GUI. Thanks.

**Comment by horar** [comment] 2017-04-09 23:29
Similar problem was reported and solved by uninstalling Anyconnect, tap drivers, openconnect-gui and then installing again openconnect-gui.
I'm closing this, when problem persist, feel free to come back.
Thanks.

**Closed by horar** 2017-04-09 23:29 UTC

**Comment by mlushpenko** [comment] 2018-04-26 18:14
@horar for me just installation of gui helped, from command line I am still getting errors connection to VPN, but via GUI with the same configuration it works, don't know why

**Comment by horar** [comment] 2018-04-26 19:51
@mlushpenko did you start command line openconnect in console with admin rights?

**Comment by mlushpenko** [comment] 2018-04-26 20:24
@horar I even have such entry in /etc/sudoers

`%admin          ALL = (ALL) NOPASSWD: /usr/local/bin/openconnect`

Maybe I still missing something, this was my command:

`openconnect -u maksym --authgroup=Registry https://vpnurl.com`

**Comment by horar** [comment] 2018-04-26 20:39
As far i remember, your setup ensure password-less start of openconnect. Please start as follow;

`sudo openconnect -u maksym --authgroup=Registry https://vpnurl.com`

**Comment by mlushpenko** [comment] 2018-04-26 20:46
thanks @horar , it worked :) feeling a bit dumb

**Comment by horar** [comment] 2018-04-26 21:19
@mlushpenko enjoy :-)
